### ISSUE TITLE
Multiple "Umbrella header for module 'SVGKit' does not include header [...] warnings

### ISSUE THREAD

**Issue by adamjansch** [SVGKit/SVGKit#687]
### New Issue Checklist

* [x] I have read and understood the [CONTRIBUTING guide](https://github.com/SVGKit/SVGKit/blob/2.x/CONTRIBUTING.md)
* [x] I have reproduced the problem while running in Xcode, and read the Console log, and acted upon any relevant error or warning messages
* [x] I have reproduced the problem while running in Xcode's Debugger, and used breakpoints to examine the actual values of variables vs the expected values
* [ ] I am not using CocoaPods, or: I am using CocoaPods, but have verified my podspec points to SVGKit v2.x

### Issue Description and Steps

We have added SVGKit to project via CocoaPods using the following line in our podfile:

    pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '3.x'

When we build our project Xcode produces multiple compiler errors relating to SVGKit headers:

> Umbrella header for module 'SVGKit' does not include header 'SVGKDefine_Private.h'
> Umbrella header for module 'SVGKit' does not include header 'SVGKImageRep.h'
> Umbrella header for module 'SVGKit' does not include header 'SVGKExporterNSImage.h'

Any ideas how to fix the warnings (without just hiding them)?

**Comment by adamgit** [comment]
Side effect of @karimhm 's recent changes to add Swift Package Mnager support?

**Comment by karimhm** [comment]
@adamgit I confirm that this is related to the recent changes to add Swift Package Manager support.
Happens only on pure 100% Objective-C projects.
 Im working on a fix.

**Comment by karimhm** [comment]
@adamgit I confirm that this is related to the recent changes to add Swift Package Manager support.
This happens only on pure/100% Objective-C projects.
Im working on a fix.

**Comment by fjtrujy** [comment]
Hello,
Just adding some more info.
I'm suffering this issue as well, but I'm using a 100% Swift project, Cocoapods 1.9.3 and Xcode 11.6

Thanks.

**Comment by timbms** [comment]
Yes, here as well. on Xcode 12, almost 100% swift project, Cocoapods 1.10.0.rc.1
We get exactly the same warnings.

**Comment by adamgit** [comment]
If @karimhm can't fix it, I'm not sure what to do here. I looked into what Swift is doing and why SPM causes these problems, but at the time no-one had an easy fix - basically: with the arrival of the SPM it's tough getting Swift and ObjC to work well together.

My assumption is that it requires some juggling of header search paths etc, but we need someone who's got both ObjC and Swift and SPM projects to test that and find a solution that works with all three :(.

**Comment by chriseplettsonos** [comment]
I'm wondering where things stand on this issue. I'm working on a project that has both Swift and Obj-C code. We have been using an old 2.x release of SVGKit, loaded via Carthage. We are looking to get off of Carthage and modernize to SPM, but when we try to use SPM to load SVGKit from the 3.x branch, we get this as an error, failing the build.

I'm just wondering if anyone has made any headway before we have to fork and try coming up with our own fix…

**Comment by nysander** [comment]
I have this warnings using Cocoapods and Xcode 12.5+ (including 13.x) but code compiles.

**Comment by joe-dialpad** [comment]
> 

this happens on swift projects using cocoapods, too.

**Comment by JoeFerrucci** [comment]
> @adamgit I confirm that this is related to the recent changes to add Swift Package Manager support. This happens only on pure/100% Objective-C projects. Im working on a fix.

@karimhm 
this happens on swift projects using cocoapods, too.

pod SVGKit 3.0.0, Xcode 13.2.1

**Comment by JoeFerrucci** [comment]
> @adamgit I confirm that this is related to the recent changes to add Swift Package Manager support. This happens only on pure/100% Objective-C projects. Im working on a fix.

@karimhm
this happens on swift projects using cocoapods, too.

pod SVGKit 3.0.0, Xcode 13.2.1

**Comment by matthewkertis** [comment]
This continues to be an issue on XCode Version 14.0

**Comment by dugupta** [comment]
I still have this issue. Do we have any fix for this?

**Comment by michalnowak061** [comment]
same here. Xcode 14.2
